const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const postcssImport = require('postcss-import');

// --- Paths ---
const projectRoot = path.resolve(__dirname, '..');
const stylesCssPath = path.resolve(projectRoot, 'src/ui/new-ui-styles.css');
const svgDirPath = path.resolve(projectRoot, 'svg');
const cssOutputPath = path.resolve(projectRoot, 'src/ui/generated-styles.ts');
const iconsOutputPath = path.resolve(projectRoot, 'src/ui/generated-icons.ts');

// --- Helper to read files safely ---
function readFileSafe(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') {
      console.warn(`Warning: File not found - ${filePath}. Skipping.`);
      return ''; // Return empty string if file doesn't exist
    } else {
      throw error; // Rethrow other errors
    }
  }
}

// --- Embed CSS --- 
async function embedCss() {
  try {
    const css = readFileSafe(stylesCssPath);
    
    // Process CSS with PostCSS to handle @import statements
    const result = await postcss([postcssImport])
      .process(css, { from: stylesCssPath });

    const combinedCss = `\n${result.css}\n`;

    const escapedCss = combinedCss
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\`')
      .replace(/\${/g, '\\${');

    const tsContent = `// Auto-generated by build script
export const embeddedStyles = \`
${escapedCss}\`;
`;
    fs.writeFileSync(cssOutputPath, tsContent, 'utf8');
    console.log(`Successfully embedded CSS into ${cssOutputPath}`);
  } catch (error) {
    console.error('Error embedding CSS:', error);
    throw error; // Re-throw to fail the build
  }
}

// --- Embed Icons --- 
function embedIcons() {
  try {
    const iconFiles = fs.readdirSync(svgDirPath).filter(file => file.endsWith('.svg'));
    let iconsObjectContent = '{\n';

    iconFiles.forEach(fileName => {
      const filePath = path.join(svgDirPath, fileName);
      let svgContent = readFileSafe(filePath);

      // *** Re-applying: Remove hardcoded fill attributes ***
      svgContent = svgContent.replace(/ fill="#[0-9a-fA-F]+"/g, ''); // Remove fill="#..."
      svgContent = svgContent.replace(/ fill="black"/g, ''); // Remove fill="black"
      svgContent = svgContent.replace(/ fill="grey"/g, ''); // Remove fill="grey"
      svgContent = svgContent.replace(/ fill="gray"/g, ''); // Remove fill="gray"
      // Remove fill-opacity as well, as it might interfere with CSS color
      svgContent = svgContent.replace(/ fill-opacity="[\d.]+"/g, ''); 
      // Add more specific removals if needed, e.g., fill="rgb(...)"
      // Important: Ensure this doesn't remove fills needed for multi-color icons, if any.
      // *** END Re-applying ***
      
      // Refined name extraction: 
      // icon.16.lock.locked.svg -> lock-locked-16
      // icon.24.text.font-size.svg -> text-font-size-24
      // checkmark.svg -> checkmark
      let iconName = fileName.replace(/\.svg$/, ''); // Remove .svg
      const sizeMatch = iconName.match(/^icon\.(\d+)\./); // Check for icon.SIZE. prefix
      let size = '';
      if (sizeMatch) {
        size = `-${sizeMatch[1]}`;
        iconName = iconName.replace(/^icon\.\d+\./, ''); // Remove prefix
      }
      iconName = iconName.replace(/\./g, '-') + size; // Replace dots with hyphens and append size

      if (iconName) {
        const escapedSvg = svgContent
          .replace(/\\/g, '\\\\')
          .replace(/`/g, '\`')
          .replace(/\${/g, '\\${');
        iconsObjectContent += `  '${iconName}': \`${escapedSvg}\`,\n`;
      }
    });

    iconsObjectContent += '};';

    const tsContent = `// Auto-generated by build script
export const iconSvgs: Record<string, string> = ${iconsObjectContent}
`;
    fs.writeFileSync(iconsOutputPath, tsContent, 'utf8');
    console.log(`Successfully embedded Icons into ${iconsOutputPath}`);

  } catch (error) {
    console.error('Error embedding Icons:', error);
    throw error; // Re-throw to fail the build
  }
}

// --- Run Steps --- 
async function run() {
  try {
    await embedCss();
    embedIcons();
  } catch (error) {
    process.exit(1);
  }
}

run(); 